### ISSUE TITLE
Compilation fails reproducibly on missing parser.h

### ISSUE THREAD

**Issue by ralphholz** [zmap/zmap#399]
I am stumbling over some strange phenomenon. This might, in fact, be a cmake bug, but it affects the build instructions for zmap as well.

I am using revision c04bc6d060f0ce1f198ff7eda6bf1a685d3b8efa, Dec 5 18:35:08 2016 -0800, on a vanilla, clean Ubuntu 16.04 LTS, with libraries apt-getted as per README.md.

I am getting this error:
/home/ralph/tmp.com/zmap/src/filter.c:12:20: fatal error: parser.h: No such file or directory

parser.h is generated by the "cmake ." before the "make -j4".

I played with this and the error occurs **only** if the following condition is met: zmap repository is cloned into a path that contains the string ".com".

Experiments, checking repository out into:
/home/ralph/github.com/zmap: fails as described above
home/ralph/tmp.com/zmap: fails as described above

In these cases, I also find a github.h and a tmp.h in my home directory - see attached.

home/ralph/tmp.org/zmap: works as expected
home/ralph/tmp.tmp/zmap: works as expected
/home/ralph/zmap: works as expected
/home/ralph/zmap/zmap: works as expected

I repeated this twice, for all of the above paths, and the results were identical on both occasions. Is this something weird in cmake or the build script?

(Note: also discussed with @dadrian over Twitter)

tmp.h and github.h are identical:
#define T_AND 257
#define T_OR 258
#define T_NUMBER 259
#define T_FIELD 260
#define T_NOT_EQ 261
#define T_GT_EQ 262
#define T_LT_EQ 263
#ifdef YYSTYPE
#undef  YYSTYPE_IS_DECLARED
#define YYSTYPE_IS_DECLARED 1
#endif
#ifndef YYSTYPE_IS_DECLARED
#define YYSTYPE_IS_DECLARED 1
typedef union {
	int int_literal;
	char *string_literal;
	struct node_st *expr;
} YYSTYPE;
#endif /* !YYSTYPE_IS_DECLARED */
extern YYSTYPE yylval;

**Comment by dadrian** [comment]
I confirmed this happens on OS X.

 (╯°□°）╯︵ ┻━┻

**Comment by ralphholz** [comment]
@dadrian Did you try to create a minimalistic ./config + cmake example? This sounds more like a cmake problem than anything else.

**Comment by dadrian** [comment]
I've confirmed that this now works with CMake 3.9.1, and updated docs.

**Comment by ralphholz-usyd** [comment]
@dadrian Meh. Just took a vanilla Ubuntu 18.04.2 LTS and cmake 3.10.2 - problem is back:

`apt-get install build-essential cmake libgmp3-dev gengetopt libpcap-dev flex byacc libjson-c-dev pkg-config libunistring-dev`
` cmake .`
`[ 40%] Building C object src/CMakeFiles/ztee.dir/topt_compat.c.o
`/home/ralph/repos/github.com/zmap/zmap/src/filter.c:12:10: fatal error: parser.h: No such file or directory
 #include "parser.h"
          ^~~~~~~~~~
compilation terminated.`

**Comment by codyprime** [comment]
Additional data point, if helpful: compiling on Fedora 29 works fine:

Versions:
`cmake version 3.14.5`
`gcc (GCC) 8.3.1 20190223 (Red Hat 8.3.1-2)`
```
commit 48dc3dd (HEAD -> master, origin/master, origin/HEAD)
Author: Zakir Durumeric
Date:   Sun May 12 11:18:20 2019 -0700

    move default setting later in zmap init (#555)
```

Compilation steps:
`git clone https://github.com/zmap/zmap`
`cd zmap`
`cmake .`
`make -j12`

**Comment by ralphholz-usyd** [comment]
@codyprime Can you please recreate the dir structure `/home/$USER/repos/github.com/zmap/zmap` and run cmake/make from that?

**Comment by codyprime** [comment]
@ralphholz-usyd Yes, sure:

```
$ mkdir -p ~/repos/github.com/zmap
$ cd ~/repos/github.com/zmap
$ git clone https://github.com/zmap/zmap
[...]

$ cd zmap
$ pwd
/home/jcody/repos/github.com/zmap/zmap

$ cmake .
-- The C compiler identification is GNU 8.3.1
-- Check for working C compiler: /usr/lib64/ccache/cc
-- Check for working C compiler: /usr/lib64/ccache/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.5.3") 
-- Checking for module 'json-c'
--   Found json-c, version 0.13.1
-- Default ZMap configuration file location is /etc/zmap
-- Checking if blacklist.conf exists there...
-- Checking if zmap.conf exists there...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jcody/repos/github.com/zmap/zmap

$ make
[...]
[ 11%] Linking C static library libzmaplib.a
[ 11%] Built target zmaplib
[ 11%] Generating parser.c
[...]
[100%] Linking C executable ztee
[100%] Built target ztee

$ ls -lhs src/zmap
244K -rwxrwxr-x. 1 jcody jcody 241K Aug 20 00:20 src/zmap
```

**Comment by ralphholz-usyd** [comment]
@codyprime Quite excellent - now we know it's the cmake that Ubuntu is shipping. Unless the -j switch does anything weird - I see that you didn't use it the second time. But I doubt it.

**Comment by codyprime** [comment]
@ralphholz-usyd I have a VM with Ubuntu 18.04, so I tried reproducing this issue.  I can confirm that with cmake version 3.10.2, and gcc 7.4.0 (as shipped with Ubuntu), if you have a directory name with a `.` in it the make process fails (e.g. `/home/jcody/github.com/zmap`).  If you build in a pathname without a `.`, it works fine (e.g. `/home/jcody/src/zmap`).  So I'd suggest either upgrading cmake, or renaming your work directory.

**Comment by ralphholz** [comment]
Yip - same as 1-2 years ago. I'll see if I can report that upstream to
Ubuntu.
