### ISSUE TITLE
Install didn't work on Ubuntu 12.10

### ISSUE THREAD

**Issue by K3r0sen** [zmap/zmap#96]
- Downloaded https://github.com/zmap/zmap/archive/master.zip
- Unziped
- Installed dependencies "sudo apt-get install libgmp3-dev libpcap-dev gengetopt byacc flex"
- installed cmake "sudo apt-get install cmake"
-  "cmake -DENABLE_HARDENING=ON"
- Start build "make"

Got Error:

marius@marius:~/webdev/zmap/zmap-master$ make
[  3%] Generating parser.c
[  6%] Generating zopt.h
[  9%] Generating lexer.c
Scanning dependencies of target zmap
[ 12%] Building C object src/CMakeFiles/zmap.dir/aesrand.c.o
[ 15%] Building C object src/CMakeFiles/zmap.dir/cyclic.c.o
In file included from /home/marius/webdev/zmap/zmap-master/src/cyclic.c:49:0:
/home/marius/webdev/zmap/zmap-master/src/../lib/includes.h:2:21: fatal error: dumbnet.h: No such file or directory
compilation terminated.
make[2]: **\* [src/CMakeFiles/zmap.dir/cyclic.c.o] Error 1
make[1]: **\* [src/CMakeFiles/zmap.dir/all] Error 2
make: **\* [all] Error 2
